#!/bin/sh

# Create a python virtual environment.
# This wrapper exists literally so that I don't have to pass the . and type -m manually, or type activate manually.

if [ $# -eq 0 ]; then
    _VENVNAME="."
else
    _VENVNAME="$1"
    shift
fi

if [ ! -d "$_VENVNAME/bin" ]; then
    python -m venv "$_VENVNAME" "$@"
fi
_REALVENV="$(realpath "$_VENVNAME")"

# Activate the venv
. "$_REALVENV/bin/activate"

# Clean up variables, since this script is also sourced.
unset _VENVNAME
unset _REALVENV
