#!/bin/sh

if [ ! "$1" = "" ]; then
  if ! awk 'BEGIN { if (ARGV[1] ~ /^[+-]?([0-9]*[.])?[0-9]+$/) exit 0; else exit 1 }' "$1" 2>/dev/null; then
    echo "Argument must be a valid float.";
    exit 1;
  fi
  SIZE="$1"
else
  SIZE="37.5"
fi

ORIGINAL="$HOME/.config/kitty/kitty.conf"
TEMP="$HOME/.config/kitty/kitty.conf.tmp"
SMALL="font_size 15"
BIG="font_size $SIZE"

mv "$ORIGINAL" "$TEMP"
cat "$TEMP" | sed "s/$SMALL/$BIG/g" > "$ORIGINAL"

nohup kitty >/dev/null 2>&1

mv "$TEMP" "$ORIGINAL"

#kill -9 $PPID
