#!/bin/sh

# Copies the (preprocessed) file to your clipboard, and opens godbolt in browser.

PP=0
if [ "$1" = "pp" ]; then
  PP=1;shift
fi

if [ ! -f "$1" ]; then
  echo "\033[1;31mPlease provide an input file.\033[0m"
  exit 1
fi

if [ "$PP" -eq 1 ]; then
  cc -E -P "$1" | xclip -selection clipboard && xdg-open https://godbolt.org &
else
  cat "$1" | xclip -selection clipboard && xdg-open https://godbolt.org &
fi
