#!/usr/bin/env bash

# List all the manually installed packages according to APT.

sudo grep -oP "Unpacking \K[^: ]+" /var/log/installer/syslog | sort -u | comm -13 /dev/stdin <(apt-mark showmanual | sort)
