#!/usr/bin/python3

# Convert markdown to HTML.

import re
import os
import sys
import base64
import subprocess
import tempfile
from shlex import split

def run(s):
  subprocess.run(split(s), check=True)

blog_mode = '--blog' in sys.argv
args = [a for a in sys.argv[1:] if a != '--blog']

if not args:
  print('Please provide a markdown file to convert.')
  exit(1)

_from = args[0]
_title =  os.path.splitext(_from)[0]+'.html'
_to = args[1] if len(args) > 1 else _title

if blog_mode:
  clean_site = os.path.expanduser("~/git/clean-site")
  stylefile = os.path.join(clean_site, "resources/style/pandoc.html")
  fontfile = os.path.join(clean_site, "resources/style/lemon.woff")
  if not os.path.exists(stylefile) or not os.path.exists(fontfile):
    print(f'Error: --blog requires ~/git/clean-site/ to be present.')
    exit(1)

  # Embed lemon.woff as base64 data URI so the output is self-contained
  with open(fontfile, "rb") as f:
    font_b64 = base64.b64encode(f.read()).decode()
  with open(stylefile) as f:
    style = f.read()
  style = style.replace("url('lemon.woff')", f"url('data:font/woff;base64,{font_b64}')")

  tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False)
  tmp.write(style)
  tmp.close()

  display_title = os.path.splitext(os.path.basename(_from))[0].replace("_", " ")
  run(f'pandoc -s --embed-resources --standalone --metadata pagetitle="{display_title}" -f markdown-smart -H {tmp.name} {_from} -o {_to}')
  os.unlink(tmp.name)

  # Post-process: fix .sourceCode style (same as generate.py)
  with open(_to) as f:
    html = f.read()
  html = re.sub(
    r"\s+\.sourceCode \{\s+background-color: transparent;\s+overflow: visible;\s+\}",
    "\n    .sourceCode {\n      font-size: 20px;\n    }",
    html, flags=re.DOTALL, count=1
  )
  with open(_to, "w") as f:
    f.write(html)
else:
  css = """<style type="text/css">
body {
    margin: auto;
    padding-right: 1em;
    padding-left: 1em;
    max-width: 44em;
    border-left: 1px solid black;
    border-right: 1px solid black;
    color: black;
    font-family: Verdana, sans-serif;
    font-size: 100%;
    line-height: 140%;
    color: #333;
}
</style>
"""

  with open("pandoc.css", "w+") as f:
    f.write(css)

  run(f'pandoc -s --embed-resources --standalone --toc --metadata pagetitle="{_title}" -H pandoc.css -fmarkdown -thtml {_from} -o {_to}')

  run('rm pandoc.css')

