#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
  echo "USAGE: mktar <output> <input>..."
elif [ "$#" -eq 1 ]; then
  echo tar -czvf "$1.tar.gz" "$1"
else
  OUT="$1.tar.gz"; shift
  echo tar -czvf "$OUT" "$@"
fi

