#!/bin/sh

WD="$(pwd)"
cd /tmp/
git clone --depth=1 https://github.com/neovim/neovim
cd neovim/
make -j \
  CMAKE_BUILD_TYPE=Release \
  CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.neovim"
make install

export PATH="$HOME/.neovim/bin:$PATH"
echo "Edited the \$PATH for this bash session."
echo "Make sure that \"~/\$HOME/.nvim/bin\" is added to \$PATH in your .bashrc."
cd "$WD"
