#!/bin/sh

echo "cd ~ && curl -sSL https://apaz.dev/setup | PRIME=1 sh"
echo "cd prime/"
echo ". .venv/bin/activate"
echo "export LD_LIBRARY_PATH=\$(python -c \"import site; print(site.getsitepackages()[0] + '/nvidia/nvjitlink/lib')\"):\$LD_LIBRARY_PATH"
echo
