#!/bin/sh

echo "curl -sSL https://apaz.dev/setup | sh"
echo "apaz-cli  $(ghp)"
echo
echo "export LD_LIBRARY_PATH=\$(python -c \"import site;print(site.getsitepackages()[0]+'/nvidia/nvjitlink/lib')\"):\$LD_LIBRARY_PATH"
echo "huggingface-cli login --token $HF_TOKEN"
echo "wandb login $WANDB_KEY"
echo
