#!/bin/sh

ENV_NAME="pytorchenv"
CURRENT_WD="$(pwd)"
TORCH_DIR="/tmp/$ENV_NAME"

if [ ! -d "$TORCH_DIR" ]; then
    echo "Building venv."
    cd /tmp
    mkdir "$ENV_NAME"
    cd "$ENV_NAME"
    python -m venv .venv
    .venv/bin/pip install torch numpy ipython
fi

TMPF="/tmp/__import_torch__.py"
echo "import torch;from torch import tensor" > $TMPF

cd "$CURRENT_WD"

"/tmp/$ENV_NAME/.venv/bin/ipython" -i "$TMPF" "$@"


