#!/bin/bash

# Activates conda and switches to the specified workspace.

# USAGE:
# In the folder with all your working repos:
# . thunder <reponame>
# In the current workspace:
# . ../thunder

WD="$(pwd)"
PROJ="lightning-thunder"
REPO="main"
CONDA_ENV="thunder-3-10-9"
if [ ! "$(echo \"$WD\" | grep $PROJ)" = "" ]; then
  cd ..
  REPO=$(echo "$WD" | awk -F "$PROJ" '{print $2}')
elif [ ! "$1" = "" ]; then
  REPO="$1"
fi

NWD="$PROJ$REPO/"
cd "$NWD" 2>/dev/null
if [ ! "$?" = "0" ]; then echo "Cannot cd to $NWD"; fi
conda activate "$CONDA_ENV" 2>/dev/null
