#!/bin/bash

# Activates conda and switches to the specified workspace.

# USAGE:
# In the folder with all your working repos:
# . thunder <reponame>
# In the current workspace:
# . ../thunder

WD="$(pwd)"
REPO="main"
if [ ! "$(echo \"$WD\" | grep lightning-thunder)" = "" ]; then
  cd ..
  REPO=$(echo "$WD" | awk -F "lightning-thunder" '{print $2}')
elif [ ! "$1" = "" ]; then
  REPO="$1"
fi

NWD="lightning-thunder$REPO/"
cd "$NWD" 2>/dev/null
if [ ! "$?" = "0" ]; then echo "Cannot cd to $NWD"; fi
conda activate thunder-3-10-9 2>/dev/null
