#!/bin/sh

# Create a python virtual environment.
# This wrapper exists literally so that I don't have to pass the . and type -m manually.

if [ $# -eq 0 ]; then
    python -m venv .
else
    python -m venv $@
fi
