#!/bin/sh

# Launch mus in xterm.

xterm                                    \
  -fa 'lemon'                            \
  -fd 'Unifont'                          \
  -fs 12                                 \
  -e 'vlc -I ncurses --no-video ~/Music/'
